import java.awt.*;
import java.io.File;
import java.util.Enumeration;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wdl
 */
public class MyJFrame extends javax.swing.JFrame {
    private Component parent;
    //String selectPath="";
    /**
     * Creates new form MyJFrame
     */
    public MyJFrame() {
        initComponents();
        setLocationRelativeTo(getOwner());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()  {
        buttonGroup_c = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_urlPrefix = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_urlPostfix = new javax.swing.JTextArea();
        jTextArea_EncodeText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton_Run = new javax.swing.JButton();
        jLabel_qr = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_R = new javax.swing.JTextArea();
        jButton_cls = new javax.swing.JButton();
        jRadioButton_JD = new javax.swing.JRadioButton();
        jRadioButton_Dynamic = new javax.swing.JRadioButton();
        jRadioButton_DES = new javax.swing.JRadioButton();
        jRadioButton_GOAGO = new javax.swing.JRadioButton();
        jRadioButton_QR = new javax.swing.JRadioButton();
        jRadioButton_lxewm= new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_filepath = new javax.swing.JTextField();
        jButton_select = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("urlPrefix:");

        jLabel2.setText("urlPostfix:");

        jTextArea_urlPrefix.setColumns(20);
        jTextArea_urlPrefix.setLineWrap(true);
        jTextArea_urlPrefix.setRows(5);
        jTextArea_urlPrefix.setText("http://wxtest.5ifapiao.com/eyun/weixin/passive/scanredirect/");
        jScrollPane1.setViewportView(jTextArea_urlPrefix);

        jTextArea_urlPostfix.setColumns(20);
        jTextArea_urlPostfix.setLineWrap(true);
        jTextArea_urlPostfix.setRows(5);
        jTextArea_urlPostfix.setText(".do");
        jScrollPane2.setViewportView(jTextArea_urlPostfix);

        jTextArea_EncodeText.setColumns(20);
        jTextArea_EncodeText.setLineWrap(true);
        jTextArea_EncodeText.setRows(5);
        jTextArea_EncodeText.setText("订单号|jdcom");

        jLabel3.setText("Text:");

        jButton_Run.setText("Run");
        jButton_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RunActionPerformed(evt);
            }
        });

        jButton2.setText("Decode");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });



        jTextArea_R.setColumns(20);
        jTextArea_R.setLineWrap(true);
        jTextArea_R.setRows(5);
        jScrollPane3.setViewportView(jTextArea_R);

        jButton_cls.setText("Clear");
        jButton_cls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clsActionPerformed(evt);
            }
        });

        buttonGroup_c.add(jRadioButton_JD);
        jRadioButton_JD.setSelected(true);
        jRadioButton_JD.setText("JD");
        jRadioButton_JD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton_JDItemStateChanged(evt);
            }
        });
        buttonGroup_c.add(jRadioButton_Dynamic);
        jRadioButton_Dynamic.setText("Dynamic");
        jRadioButton_Dynamic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton_DynamicItemStateChanged(evt);
            }
        });
        buttonGroup_c.add(jRadioButton_DES);
        jRadioButton_DES.setText("AES");
        jRadioButton_DES.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {

                jRadioButton_AESItemStateChanged(evt);
            }
        });
        buttonGroup_c.add(jRadioButton_GOAGO);
        jRadioButton_GOAGO.setText("GOAGO");
        jRadioButton_GOAGO.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton_GOAGOItemStateChanged(evt);
            }
        });
        buttonGroup_c.add(jRadioButton_lxewm);
        jRadioButton_lxewm.setText("lxewm");
        jRadioButton_lxewm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton_lxewmItemStateChanged(evt);
            }
        });

        buttonGroup_c.add(jRadioButton_QR);
        jRadioButton_QR.setText("QR");
        jRadioButton_QR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {

                jRadioButton_QRItemStateChanged(evt);
            }
        });
        jLabel4.setText("公钥/私钥位置:");

        jButton_select.setText("....");
        jButton_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selectActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel2))
                                                                .addGap(2, 2, 2))
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jTextArea_EncodeText)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                        .addComponent(jButton_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(62, 62, 62)
                                                                                        .addComponent(jButton_cls)
                                                                                        .addGap(62, 62, 62))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                        .addComponent(jTextField_filepath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(25, 25, 25)))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jButton_select)
                                                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(38, 38, 38)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jRadioButton_JD)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jRadioButton_Dynamic)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jRadioButton_lxewm)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jRadioButton_DES)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jRadioButton_GOAGO)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jRadioButton_QR)))
                                                .addGap(27, 27, 27))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jTextArea_EncodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(jRadioButton_GOAGO)
                                                                                        .addComponent(jRadioButton_Dynamic)
                                                                                        .addComponent(jRadioButton_DES)
                                                                                        .addComponent(jRadioButton_QR)
                                                                                        .addComponent(jRadioButton_lxewm)
                                                                                        .addComponent(jRadioButton_JD))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                                        .addGroup(layout.createSequentialGroup()

                                                                                .addGap(7, 7, 7)))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jTextField_filepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButton_select)))
                                                        .addComponent(jLabel_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton_Run)
                                                        .addComponent(jButton_cls))))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton_selectActionPerformed(java.awt.event.ActionEvent evt) {

        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);//设置只能选择目录和目录下文件
        String path = System.getProperty("user.dir");
        chooser.setCurrentDirectory(new File(path));
        int returnVal = chooser.showOpenDialog(parent);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String selectPath = chooser.getSelectedFile().getPath();//选择文件路径
            jTextField_filepath.setText(selectPath); //把目录传给小文本框
            System.out.println("-----------------------------"+jTextField_filepath.getText());
        }
    }
    private void jButton_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RunActionPerformed
        String path=jTextField_filepath.getText();
        // TODO add your handling code here:
        try
        {
            String Radio_S="false";  
            Enumeration<AbstractButton> radioBtns=buttonGroup_c.getElements();  
            while (radioBtns.hasMoreElements()) {  
                AbstractButton btn = radioBtns.nextElement();  
                if(btn.isSelected()){  
                    Radio_S=btn.getText();
                    break;  
                }
            }
            if(Radio_S.equals("JD")){
                jLabel2.setText("urlPostfix:");
                String En_str=Base64Encoding.encryptBASE64(PublicSecretRSA.publicEncrypt(jTextArea_EncodeText.getText(),path));
                jTextArea_R.append("加密后:" + En_str + "\n");
                System.out.println("OUT......\n" + En_str);
                String RURL = jTextArea_urlPrefix.getText() + En_str + jTextArea_urlPostfix.getText();
                jLabel_qr.setIcon(new ImageIcon(QRCodeEncoderHandler.encoderQRCode(RURL)));
                jTextArea_R.append("拼接后URL为:\n" + RURL + "\n");
            }else if(Radio_S.equals("Dynamic")){
                jLabel2.setText("urlPostfix:");
                String En_str=Base64Encoding.encryptBASE64(PublicSecretRSA.publicEncrypt(jTextArea_EncodeText.getText(),path));
                jTextArea_R.append("加密后:" + En_str + "\n");
                String RURL = jTextArea_urlPrefix.getText() + En_str + jTextArea_urlPostfix.getText();
                jLabel_qr.setIcon(new ImageIcon(QRCodeEncoderHandler.encoderQRCode(RURL)));
                jTextArea_R.append("拼接后URL为:\n" + RURL + "\n");
            }else if(Radio_S.equals("GOAGO")){
                jLabel2.setText("urlPostfix:");
                String En_str=Base64Util.encodeutf8(jTextArea_EncodeText.getText());
                System.out.println("OUT......\n" + En_str);
                String RURL = jTextArea_urlPrefix.getText() + En_str + jTextArea_urlPostfix.getText();
                jLabel_qr.setIcon(new ImageIcon(QRCodeEncoderHandler.encoderQRCode(RURL)));
                jTextArea_R.append("拼接后URL为:\n" + RURL + "\n");
            }else if(Radio_S.equals("QR")){
                jLabel2.setText("urlPostfix:");
                //String path = System.getProperty("user.dir");
                String QText = jTextArea_urlPrefix.getText() ;
                jLabel_qr.setIcon(new ImageIcon(QRCodeEncoderHandler.encoderQRCode(QText)));
                //QRCodeEncoderHandler.encoderQRCode(QText, path + "\\" + "code.jpg");
                //jLabel_qr.setIcon(new ImageIcon(ImageIO.read(new File(path+ "\\"+ "code.jpg"))));
            }else if(Radio_S.equals("AES")){
                jLabel2.setText("password:");
                String En_str=AuthenticationUtil.getEncrypt(jTextArea_urlPostfix.getText(),jTextArea_EncodeText.getText());
                jTextArea_R.append("加密后:" + En_str + "\n");
           /* }else if(Radio_S.equals("AES")){
                jLabel2.setText("password:");
                String En_str=DesUtil.encrypt(jTextArea_EncodeText.getText(),jTextArea_urlPostfix.getText());
                jTextArea_R.append("加密后:" + En_str + "\n");
                String RURL = jTextArea_urlPrefix.getText() + En_str;
                jLabel_qr.setIcon(new ImageIcon(QRCodeEncoderHandler.encoderQRCode(RURL)));
                jTextArea_R.append("拼接后URL为:\n" + RURL + "\n");*/
            }else if(Radio_S.equals("lxewm")){
                //String En_str=AesUtils.encrypt(jTextArea_EncodeText.getText(),jTextArea_urlPostfix.getText());
                String En_str=GenerateSigna.generateSigna(jTextArea_EncodeText.getText()+jTextArea_urlPostfix.getText(),jTextArea_urlPostfix.getText());
                jTextArea_R.append("加密后:" + En_str + "\n");
                String RURL = jTextArea_urlPrefix.getText() + jTextArea_EncodeText.getText()+"&SIGN="+En_str;
                jLabel_qr.setIcon(new ImageIcon(QRCodeEncoderHandler.encoderQRCode(RURL)));
                jTextArea_R.append("拼接后URL为:\n" + RURL + "\n");
            }
        }
        catch(Exception e){
            System.out.println("Error....." + e.toString());
        }
    }//GEN-LAST:event_jButton_RunActionPerformed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String str = jTextArea_EncodeText.getText();
        String path = jTextArea_EncodeText.getText();
        try {
            String decryptResult = PublicSecretRSA.privateDecrypt(Base64Encoding.decryptBASE64(str),path);
            System.out.println("decode..." + decryptResult);
            jTextArea_R.setText("解码结果:\n" + decryptResult + "\n");
        }
        catch(Exception e){
            System.out.println("de...." + e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton_clsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clsActionPerformed
        // TODO add your handling code here:
        jTextArea_R.setText("");
    }//GEN-LAST:event_jButton_clsActionPerformed
    private void jRadioButton_GOAGOItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton_GOAGOItemStateChanged
        jLabel1.setText("urlPrefix:");
        jLabel2.setText("urlPostfix:");
        jLabel3.setText("Text:");
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(false);
        jTextField_filepath.setVisible(false);
        jButton_select.setVisible(false);
        jScrollPane2.setVisible(true);
        jTextArea_EncodeText.setVisible(true);
        // TODO add your handling code here:
        jTextArea_urlPrefix.setText("http://wxcs.5ifapiao.com/eyun/qysm/totitleconfirm/gooagoo/");
        jTextArea_urlPostfix.setText(".do");
        jTextArea_EncodeText.setText("lsh|ddh|nsrsbh");
    }//GEN-LAST:event_jRadioButton_GOAGOItemStateChanged
    private void jRadioButton_DynamicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton_DynamicItemStateChanged
        jLabel1.setText("urlPrefix:");
        jLabel2.setText("urlPostfix:");
        jLabel3.setText("Text:");
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel4.setText("公钥/私钥位置:");
        jTextField_filepath.setVisible(true);
        jTextField_filepath.setText("");
        jButton_select.setVisible(true);
        jScrollPane2.setVisible(true);
        jTextArea_EncodeText.setVisible(true);
        // TODO add your handling code here:
        jTextArea_urlPrefix.setText("http://wxtest.5ifapiao.com/invoice_manager/scan/");
        jTextArea_urlPostfix.setText("|online:v1.0.do");
        jTextArea_EncodeText.setText("开票日期（格式：YYYYMMDDHHMMSS）|发票代码|发票号码|开票方名称|受票方名称|价税合计");
    }//GEN-LAST:event_jRadioButton_DynamicItemStateChanged
    private void jRadioButton_AESItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton_AESItemStateChanged
        jLabel1.setText("urlPrefix:");
        jLabel2.setText("password:");
        jLabel3.setText("content:");
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(false);
        jScrollPane2.setVisible(true);
        jTextField_filepath.setVisible(false);
        jTextArea_EncodeText.setVisible(true);
        jButton_select.setVisible(false);
        // TODO add your handling code here:
        jTextArea_urlPrefix.setText("");
        //jTextArea_urlPostfix.setText("8a9b9755-3c2b-4ceb-acfe-3ac30cb63cd3");
        jTextArea_urlPostfix.setText("5050#@jd");
        jTextArea_EncodeText.setText("{\"status\":\"1\",\"fpdm\":\"123456789012\",\"fphm\":\"12345678\",\"ddh\":\"12345678\",\"appid\":\"aaa\",\"lsh\":\"123456\"}");
    }//GEN-LAST:event_jRadioButton_AESItemStateChanged
    private void jRadioButton_JDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton_JDItemStateChanged
        jLabel1.setText("urlPrefix:");
        jLabel2.setText("urlPostfix:");
        jLabel3.setText("Text:");
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel4.setText("公钥/私钥位置:");
        jScrollPane2.setVisible(true);
        jTextField_filepath.setVisible(true);
        jTextField_filepath.setText("");
        jTextArea_EncodeText.setVisible(true);
        jButton_select.setVisible(true);
        // TODO add your handling code here:
        jTextArea_urlPrefix.setText("http://wxtest.5ifapiao.com/eyun/weixin/passive/scanredirect/");
        jTextArea_urlPostfix.setText(".do");
        jTextArea_EncodeText.setText("订单号|jdcom");
    }//GEN-LAST:event_jRadioButton_JDItemStateChanged
    private void jRadioButton_QRItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton_QRItemStateChanged
        jLabel1.setText("Content:");
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jTextField_filepath.setVisible(false);
        jButton_select.setVisible(false);
        // TODO add your handling code here:
        jTextArea_urlPrefix.setText("01,04,011001600111,16740742,7.52,20161020,52152068363038708072,0116");
        jScrollPane2.setVisible(false);
        jTextArea_EncodeText.setVisible(false);
    }//GEN-LAST:event_jRadioButton_QRItemStateChanged
    private void jRadioButton_lxewmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton_AESItemStateChanged
        jLabel1.setText("urlPrefix:");
        jLabel2.setText("password:");
        jLabel3.setText("content:");
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(false);
        jScrollPane2.setVisible(true);
        jTextField_filepath.setVisible(false);
        jTextArea_urlPostfix.setText("3m7t3ZvcokwScLqaEXfSTbb69Au0nFkX");
        jTextArea_EncodeText.setVisible(true);
        jButton_select.setVisible(false);
        jTextArea_urlPostfix.setVisible(true);
        // TODO add your handling code here:
        jTextArea_urlPrefix.setText("https://wx.5ifapiao.com/myinvoice-dynamic-invoice/html/wxscaninvoice/getMsgTransfer.html?");
        //jTextArea_urlPostfix.setText("8a9b9755-3c2b-4ceb-acfe-3ac30cb63cd3");
        jTextArea_EncodeText.setText("NSRSBH=211382774648564&XSDBH=2018010300290001837283&XSRQ=201801053");
    }//GEN-LAST:event_jRadioButton_AESItemStateChanged
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_c;
    private javax.swing.JButton jButton_select;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Run;
    private javax.swing.JButton jButton_cls;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_qr;
    private javax.swing.JRadioButton jRadioButton_GOAGO;
    private javax.swing.JRadioButton jRadioButton_JD;
    private javax.swing.JRadioButton jRadioButton_DES;
    private javax.swing.JRadioButton jRadioButton_Dynamic;
    private javax.swing.JRadioButton jRadioButton_QR;
    private javax.swing.JRadioButton jRadioButton_lxewm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea_R;
    private javax.swing.JTextArea jTextArea_urlPostfix;
    private javax.swing.JTextArea jTextArea_urlPrefix;
    private javax.swing.JTextArea jTextArea_EncodeText;
    private javax.swing.JTextField jTextField_filepath;

    // End of variables declaration//GEN-END:variables
}
